---
- name: Install packages
  apt:
    name: '{{ pkgs_to_add }}'
    update_cache: no
    state: present
  when: pkgs_to_add is defined and pkgs_to_add
- name: Remove packages
  apt:
    name: '{{ pkgs_to_remove }}'
    state: absent
  when: pkgs_to_remove is defined and pkgs_to_remove

- name: Install PiP packages
  pip:
    requirements: "{{ role_path  }}/files/pip_site_requirements.txt"

