---
- name: Install packages
  apt:
    name: '{{ pkgs_to_add }}'
    update_cache: yes
    state: present
  when: pkgs_to_add is defined and pkgs_to_add
- name: Remove packages
  apt:
    name: '{{ pkgs_to_remove }}'
    state: absent
  when: pkgs_to_remove is defined and pkgs_to_remove

- name: Install PiP packages
  pip:
    name: '{{ pip_pkgs }}'
    state: present
  when: pip_pkgs is defined and pip_pkgs

