colorscheme ron

" turn off auto adding comments on next line
" so you can cut and paste reliably
" http://vimdoc.sourceforge.net/htmldoc/change.html#fo-table
set fo=tcq
set nocompatible
set modeline

syntax on

" set default comment color to cyan instead of darkblue
" which is not very legible on a black background
highlight comment ctermfg=cyan

set tabstop=2
set expandtab
set softtabstop=2
set shiftwidth=2
set maxmempattern=5000
set wrap                        " Show long lines on multiple rows
set number                      " Show line numbers

highlight LiteralTabs ctermbg=darkgreen guibg=darkgreen
match LiteralTabs /\s\  /
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

" Show me a ruler
set ruler

" Enable indentation matching for =>'s
filetype plugin indent on

" NerdTree shortcut
map <C-n> :NERDTreeToggle<CR>

" Paste on/off shortcuts
map <C-v> :set paste<CR>
map <C-p> :set nopaste<CR>

